MK_FILES := $(shell find . -name "*.mk")
include $(MK_FILES)


$(tar): tar

help:
	@echo "Makefile help"
	@echo "usage: tar=<target>. targets:"
	@echo "  help: this help"
	@echo "  all: build all targets"
	@echo "  clean: remove all targets"
	@echo "  ------------------------------"
	@echo "  mct: mip core test"